name: Local Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "VITE_BACKEND_HOST=${{ variables.VITE_BACKEND_HOST }}" > .env
          echo "VITE_ACCESS_TOKEN=${{ secrets.VITE_ACCESS_TOKEN }}" > .env

      - name: Start Docker Containers
        run: |
          npm run up
